### ISSUE TITLE
Format all code according to style guide

### ISSUE THREAD

**Issue by albertyw** [cellabus/apple_dep_client#17]
https://github.com/bbatsov/rubocop seems like a good place to start

**Comment by hrs** [comment]
Might I also suggest [thoughtbot's style guide](https://github.com/thoughtbot/guides/tree/master/style)?

**Comment by albertyw** [comment]
![obama-not-bad](https://cloud.githubusercontent.com/assets/3151040/10590944/6a8dbda2-7668-11e5-95e9-bc4c9317adb3.png)
